### PR TITLE
Setup project

### PR DESCRIPTION
**Pull request by pior**
- Vendorize dependencies (with working versions)
- Import update-dependencies script
- Update project name to lb-collector
- Add the dev.yml file

/cc @jarthorn @ibawt

### CODE REVIEW

**Comment by jarthorn** [comment]
Shouldn't we just work directly against `https://github.com/Shopify/lb-collector` ?

**Comment by ibawt** [comment]
Yes please remake the repo in the org. Don't fork from GitHub as it should be private.

**Comment by ibawt** [comment]
you could just literally copy the main.go there's not much in here tbh.

**Comment by pior** [comment]
1. yes this PR should have been against the Shopify repo, I'm not sure how it defaulted to the source repo...
2. I just learned that you can't switch a publicly forked repo to private (which makes sense)

**Pull request closed without merging**
